export const PANEL_COUNT_PER_FLOOR = 10;
export const TIME_UNTIL_EVERYONE_ON_SCREEN = 105 * 1000;

export const AMBIENCE_NIGHT = 'AMBIENCE_NIGHT';
export const MUSIC_OPENING = 'MUSIC_OPENING';
export const MUSIC_MAIN = 'MUSIC_MAIN';
export const MUSIC_MAIN_VOX = 'MUSIC_MAIN_VOX';
export const STUDENTS_TALKING = 'STUDENTS_TALKING';
export const CHEERING = 'CHEERING';
export const CLAPPING = 'CLAPPING';